language: objective-c

cache: cocoapods

branches:
 only:
 - master

before_install:
  - sudo gem install xcpretty

osx_image: xcode7.1

script: xcodebuild -scheme SwiftSerializer -workspace swift-serializer.xcworkspace -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

